// Single source of truth for site-wide identity, URLs, and social profiles.
// Imported by metadata (layout), sitemap, robots, and JSON-LD builders so the
// domain / name / socials never drift apart across those files.

export const siteConfig = {
  url: "https://kevinchen.com.au",
  name: "Kevin Chen",
  title: "Kevin Chen — Engineer & Creative Developer",
  description:
    "Portfolio of Kevin Chen — engineer and creative developer working across robotics, embedded systems, software, and photography.",
  jobTitle: "Engineer & Creative Developer",
  locale: "en_AU",
  // Portrait used for the Person schema / avatar. The social share card is a
  // dedicated 1200x630 image generated by app/opengraph-image.tsx.
  image: "/images/KevinChen.jpg",
  knowsAbout: [
    "Robotics",
    "Embedded Systems",
    "Software Engineering",
    "Computer Engineering",
    "Full-Stack Development",
    "Photography",
  ],
  socials: {
    linkedin: "https://www.linkedin.com/in/kevinchenengineer/",
    github: "https://github.com/KevinChen2211",
    instagram: "https://www.instagram.com/kewinchen_/",
  },
} as const;

// Profiles that all point at the same real-world person. Used for the
// schema.org `sameAs` property, which helps search engines connect the site to
// Kevin's other verified profiles (a strong entity/knowledge-graph signal).
export const sameAs: string[] = Object.values(siteConfig.socials);

// Resolve a site-relative path to an absolute URL (schema.org wants absolute).
export function absoluteUrl(path: string): string {
  if (/^https?:\/\//.test(path)) return path;
  return `${siteConfig.url}${path.startsWith("/") ? "" : "/"}${path}`;
}
